[package]
name = "home_space"
publish = false
version = "0.1.0"
edition = "2021"
description = "Home space CLI"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.19" }
