# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/
# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-13T17:36:15Z"
  labels:
    app: postgre
  name: postgre
spec:
  ports:
  - name: "5432"
    nodePort: 31589
    port: 5432
    targetPort: 5432
  selector:
    app: postgre
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-03-13T17:36:15Z"
  labels:
    app: postgre
  name: postgre
spec:
  containers:
  - args:
    - postgres
    image: docker.io/library/postgres:latest
    name: postgre
    ports:
    - containerPort: 5432
      hostPort: 5432
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: mnt-storage-db-postgre-host-0
    env:
    - name: POSTGRES_PASSWORD
      value: 44X7WEsJuUbrxk2rh#V*iyM&i
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: LANG
      value: en_US.utf8
  volumes:
  - hostPath:
      path: /mnt/storage/db/postgre
      type: Directory
    name: mnt-storage-db-postgre-host-0
